import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="header">
          <div className="container flex">
            <div className="w-1/3">
              Menu 
            </div>
            <div className="header-logo w-1/3 flex items-center">
              <Link href="/" title="Go to home page" style={{margin: 'auto'}}>
                <Image
                  src="/images/carreb-logo-100.png"
                  alt="Carreb logo"
                  style={{
                    width: 'auto',
                    height: '50px',
                    margin: 'auto'
                  }}
                  height={50}
                  width={100}
                  priority
                />
              </Link>
            </div>
            <div className="header-account w-1/3">
              <a href="" title="Login to your account">Login</a> | <a href="" title="Go to Sign up">Sign up</a>
            </div>
          </div>
        </div>

        {children}
        
        <footer className="m-auto">
          <div className="container m-auto">
            <div className="cols flex">
              <div className="w-2/4 text-left">
                <Image
                  src="/images/carreb-logo-100.png"
                  alt="Carreb logo"
                  style={{
                    width: 'auto',
                    height: '50px',
                  }}
                  height={50}
                  width={100}
                  priority
                />
                <p className="pt-4 font-semibold">Save Costs. Save the Planet.</p>
              </div>
              <div className="w-1/4">
                  <ul>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                  </ul>
              </div>
              <div className="w-1/4">
                  <ul>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                    <li><Link href="" title="View Page 1">Link a1</Link></li>
                  </ul>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
